query allSpecies($after: String, $first: Int, $before: String, $last: Int, $after1: String, $first1: Int, $before1: String, $last1: Int, $after2: String, $first2: Int, $before2: String, $last2: Int, $after3: String, $first3: Int, $before3: String, $last3: Int, $after4: String, $first4: Int, $before4: String, $last4: Int, $after5: String, $first5: Int, $before5: String, $last5: Int, $after6: String, $first6: Int, $before6: String, $last6: Int){
    allSpecies(after: $after6, first: $first6, before: $before6, last: $last6){
        pageInfo{
            hasNextPage
            hasPreviousPage
            startCursor
            endCursor
        }
        edges{
            node{
                name
                classification
                designation
                averageHeight
                averageLifespan
                eyeColors
                hairColors
                skinColors
                language
                homeworld{
                    name
                    diameter
                    rotationPeriod
                    orbitalPeriod
                    gravity
                    population
                    climates
                    terrains
                    surfaceWater
                    residentConnection(after: $after, first: $first, before: $before, last: $last){
                        totalCount
                    }
                    filmConnection(after: $after1, first: $first1, before: $before1, last: $last1){
                        totalCount
                    }
                    created
                    edited
                    id
                }
                personConnection(after: $after2, first: $first2, before: $before2, last: $last2){
                    pageInfo{
                        hasNextPage
                        hasPreviousPage
                        startCursor
                        endCursor
                    }
                    edges{
                        cursor
                    }
                    totalCount
                    people{
                        name
                        birthYear
                        eyeColor
                        gender
                        hairColor
                        height
                        mass
                        skinColor
                        created
                        edited
                        id
                    }
                }
                filmConnection(after: $after3, first: $first3, before: $before3, last: $last3){
                    pageInfo{
                        hasNextPage
                        hasPreviousPage
                        startCursor
                        endCursor
                    }
                    edges{
                        cursor
                    }
                    totalCount
                    films{
                        title
                        episodeID
                        openingCrawl
                        director
                        producers
                        releaseDate
                        created
                        edited
                        id
                    }
                }
                created
                edited
                id
            }
            cursor
        }
        totalCount
        species{
            name
            classification
            designation
            averageHeight
            averageLifespan
            eyeColors
            hairColors
            skinColors
            language
            homeworld{
                name
                diameter
                rotationPeriod
                orbitalPeriod
                gravity
                population
                climates
                terrains
                surfaceWater
                created
                edited
                id
            }
            personConnection(after: $after4, first: $first4, before: $before4, last: $last4){
                totalCount
            }
            filmConnection(after: $after5, first: $first5, before: $before5, last: $last5){
                totalCount
            }
            created
            edited
            id
        }
    }
}