query allVehicles($after: String, $first: Int, $before: String, $last: Int, $after1: String, $first1: Int, $before1: String, $last1: Int, $after2: String, $first2: Int, $before2: String, $last2: Int, $after3: String, $first3: Int, $before3: String, $last3: Int, $after4: String, $first4: Int, $before4: String, $last4: Int){
    allVehicles(after: $after4, first: $first4, before: $before4, last: $last4){
        pageInfo{
            hasNextPage
            hasPreviousPage
            startCursor
            endCursor
        }
        edges{
            node{
                name
                model
                vehicleClass
                manufacturers
                costInCredits
                length
                crew
                passengers
                maxAtmospheringSpeed
                cargoCapacity
                consumables
                pilotConnection(after: $after, first: $first, before: $before, last: $last){
                    pageInfo{
                        hasNextPage
                        hasPreviousPage
                        startCursor
                        endCursor
                    }
                    edges{
                        cursor
                    }
                    totalCount
                    pilots{
                        name
                        birthYear
                        eyeColor
                        gender
                        hairColor
                        height
                        mass
                        skinColor
                        created
                        edited
                        id
                    }
                }
                filmConnection(after: $after1, first: $first1, before: $before1, last: $last1){
                    pageInfo{
                        hasNextPage
                        hasPreviousPage
                        startCursor
                        endCursor
                    }
                    edges{
                        cursor
                    }
                    totalCount
                    films{
                        title
                        episodeID
                        openingCrawl
                        director
                        producers
                        releaseDate
                        created
                        edited
                        id
                    }
                }
                created
                edited
                id
            }
            cursor
        }
        totalCount
        vehicles{
            name
            model
            vehicleClass
            manufacturers
            costInCredits
            length
            crew
            passengers
            maxAtmospheringSpeed
            cargoCapacity
            consumables
            pilotConnection(after: $after2, first: $first2, before: $before2, last: $last2){
                totalCount
            }
            filmConnection(after: $after3, first: $first3, before: $before3, last: $last3){
                totalCount
            }
            created
            edited
            id
        }
    }
}