query vehicle($after: String, $first: Int, $before: String, $last: Int, $after1: String, $first1: Int, $before1: String, $last1: Int, $after2: String, $first2: Int, $before2: String, $last2: Int, $after3: String, $first3: Int, $before3: String, $last3: Int, $after4: String, $first4: Int, $before4: String, $last4: Int, $after5: String, $first5: Int, $before5: String, $last5: Int, $after6: String, $first6: Int, $before6: String, $last6: Int, $after7: String, $first7: Int, $before7: String, $last7: Int, $after8: String, $first8: Int, $before8: String, $last8: Int, $after9: String, $first9: Int, $before9: String, $last9: Int, $after10: String, $first10: Int, $before10: String, $last10: Int, $after11: String, $first11: Int, $before11: String, $last11: Int, $id: ID, $vehicleID: ID){
    vehicle(id: $id, vehicleID: $vehicleID){
        name
        model
        vehicleClass
        manufacturers
        costInCredits
        length
        crew
        passengers
        maxAtmospheringSpeed
        cargoCapacity
        consumables
        pilotConnection(after: $after10, first: $first10, before: $before10, last: $last10){
            pageInfo{
                hasNextPage
                hasPreviousPage
                startCursor
                endCursor
            }
            edges{
                node{
                    name
                    birthYear
                    eyeColor
                    gender
                    hairColor
                    height
                    mass
                    skinColor
                    homeworld{
                        name
                        diameter
                        rotationPeriod
                        orbitalPeriod
                        gravity
                        population
                        climates
                        terrains
                        surfaceWater
                        created
                        edited
                        id
                    }
                    filmConnection(after: $after, first: $first, before: $before, last: $last){
                        totalCount
                    }
                    species{
                        name
                        classification
                        designation
                        averageHeight
                        averageLifespan
                        eyeColors
                        hairColors
                        skinColors
                        language
                        created
                        edited
                        id
                    }
                    starshipConnection(after: $after1, first: $first1, before: $before1, last: $last1){
                        totalCount
                    }
                    vehicleConnection(after: $after2, first: $first2, before: $before2, last: $last2){
                        totalCount
                    }
                    created
                    edited
                    id
                }
                cursor
            }
            totalCount
            pilots{
                name
                birthYear
                eyeColor
                gender
                hairColor
                height
                mass
                skinColor
                homeworld{
                    name
                    diameter
                    rotationPeriod
                    orbitalPeriod
                    gravity
                    population
                    climates
                    terrains
                    surfaceWater
                    residentConnection(after: $after3, first: $first3, before: $before3, last: $last3){
                        totalCount
                    }
                    filmConnection(after: $after4, first: $first4, before: $before4, last: $last4){
                        totalCount
                    }
                    created
                    edited
                    id
                }
                filmConnection(after: $after5, first: $first5, before: $before5, last: $last5){
                    pageInfo{
                        hasNextPage
                        hasPreviousPage
                        startCursor
                        endCursor
                    }
                    edges{
                        cursor
                    }
                    totalCount
                    films{
                        title
                        episodeID
                        openingCrawl
                        director
                        producers
                        releaseDate
                        created
                        edited
                        id
                    }
                }
                species{
                    name
                    classification
                    designation
                    averageHeight
                    averageLifespan
                    eyeColors
                    hairColors
                    skinColors
                    language
                    homeworld{
                        name
                        diameter
                        rotationPeriod
                        orbitalPeriod
                        gravity
                        population
                        climates
                        terrains
                        surfaceWater
                        created
                        edited
                        id
                    }
                    personConnection(after: $after6, first: $first6, before: $before6, last: $last6){
                        totalCount
                    }
                    filmConnection(after: $after7, first: $first7, before: $before7, last: $last7){
                        totalCount
                    }
                    created
                    edited
                    id
                }
                starshipConnection(after: $after8, first: $first8, before: $before8, last: $last8){
                    pageInfo{
                        hasNextPage
                        hasPreviousPage
                        startCursor
                        endCursor
                    }
                    edges{
                        cursor
                    }
                    totalCount
                    starships{
                        name
                        model
                        starshipClass
                        manufacturers
                        costInCredits
                        length
                        crew
                        passengers
                        maxAtmospheringSpeed
                        hyperdriveRating
                        MGLT
                        cargoCapacity
                        consumables
                        created
                        edited
                        id
                    }
                }
                vehicleConnection(after: $after9, first: $first9, before: $before9, last: $last9){
                    pageInfo{
                        hasNextPage
                        hasPreviousPage
                        startCursor
                        endCursor
                    }
                    edges{
                        cursor
                    }
                    totalCount
                    vehicles{
                        name
                        model
                        vehicleClass
                        manufacturers
                        costInCredits
                        length
                        crew
                        passengers
                        maxAtmospheringSpeed
                        cargoCapacity
                        consumables
                        created
                        edited
                        id
                    }
                }
                created
                edited
                id
            }
        }
        filmConnection(after: $after11, first: $first11, before: $before11, last: $last11){
            totalCount
        }
        created
        edited
        id
    }
}